from nmsAnalysis import nmsAnalysis
from groundTruthFN import GroundTruthFN
from optimised_nms import optimisedNMS
import time
import os

def evaluateFN(annotationTrain,annotationValidation,catFocus=None):

    fn_validation = GroundTruthFN(annotationValidation,dataType="validation",catFocus=catFocus)
    print("Evaluate false negatives generated by nms on validation dataset....")
    time.sleep(3)
    fn_validation.runAnalysis()
    print("\n Done. \n")
    print("Evaluate false negatives generated by nms on training dataset....")
    fn_train = GroundTruthFN(annotationTrain,dataType="train",catFocus=catFocus)
    time.sleep(3)
    fn_train.runAnalysis()
    print("\n Done. \n")
    
def main(models,imagesPath,annotationValidation,catFocus = None,number_IoU_thresh=50,overall = True,evaluateFNnms = True,annotationTrain = None):
    
    if evaluateFN and annotationTrain == None:
        print("Please input an annotation file for the training set")
        raise ReferenceError
        
    if evaluateFNnms:
        evaluateFN(annotationTrain,annotationValidation,catFocus=catFocus)
    
    print("Starting analysis only with validation dataset... \n")
    analyser = nmsAnalysis(models,imagesPath,annotationValidation,catFocus=catFocus,number_IoU_thresh = number_IoU_thresh,overall=overall)
    time.sleep(2)
    analyser.with_train = False
    analyser.runAnalysis()
    
    print("\n Starting analysis mixed with training dataset... \n")
    time.sleep(2)
    analyser.with_train = True
    analyser.runAnalysis()


def getResult(models,annotationValidation,catFocus = None):
    """Once one get the all the required files. Check your models directort to get the result """
    optimiser = optimisedNMS(models,None,annotationValidation,catFocus=catFocus)
    # optimiser.compare_model()
    # for model in models:
    #     optimiser.overallArgmax(model)
    # optimiser.plotOverall()
    optimiser.writeMapIoU()

models = [
    "ssd_mobilenet_v1_fpn"
]
imagesPath = "cocoapi/val2017"
annotationTrain = "cocoapi/annotations/instances_train2017.json"
annotationValidation = "cocoapi/annotations/instances_val2017.json"

#Set to None if you wish to work on all categories
catFocus = ["bicycle"]

main(models,imagesPath,annotationValidation,annotationTrain= annotationTrain,catFocus=catFocus,overall=True,evaluateFNnms=False)

getResult(models,annotationValidation,catFocus=catFocus)